# Cấu hình cơ bản cho Air
root = "."  # Thư mục gốc của dự án
tmp_dir = "tmp"  # Thư mục tạm thời để build

[build]
  bin = "main"  # File binary output
  cmd = "go build -o main ."  # Lệnh build
  exclude_dir = ["tmp", "vendor"]  # Bỏ qua các thư mục này

[watcher]
  extensions = ["go", "tpl", "tmpl"]  # Theo dõi file Go và template
  dirs = ["."]
